### ISSUE TITLE
warning: format attribute "date" not supported

### ISSUE THREAD

**Issue by hminds-ritesh** [java-json-tools/json-schema-validator#103]
Hi, 

I have a JSON schema which has a property "BIRTH_DATE" with format as "date". 

"BIRTH_DATE" : { 
               "description" : "BIRTH DATE",
    "format" : "date",
    "type" : "string"
},

Whenever I try to validate a json payload after this schema, the validator succeeds but shows up a warning:

warning: format attribute "date" not supported
    level: "warning"
    schema: {"loadingURI":"#","pointer":"/definitions/MemberDemographicJsSchema/properties/BIRTH_DATE"}
    domain: "validation"
    keyword: "format"
    attribute: "date"

Am I doing anything wrong here? Or json validator does not support date format? If later, then how do I validate the date?

Regards,
Ritesh

**Comment by girish-pisharath** [comment]
Hi @fge this is still giving me the same error even after changing the $schema.Please help.
