### ISSUE TITLE
JsonSchemaFactoryBuilder not able to create a JsonSchemaFactory in Android

### ISSUE THREAD

**Issue by ascoril** [java-json-tools/json-schema-validator#153]
JsonSchemaFactoryBuilder factoryBuilder = JsonSchemaFactory.newBuilder(); 

throws an exception " android zygoteinit$methodandargscaller "

http://developer.oesf.biz/em/developer/reference/durian/com/android/internal/os/ZygoteInit.MethodAndArgsCaller.html

android sdk details:

target sdk is 19
min sdk version is 14

**Comment by fge** [comment]
Huh...

Sorry, but I don't do Android development at all.

And honestly I don't understand why this exception is thrown at all from what I read of it. It's just like the package you use doesn't like static factory methods or something... In any event, I believe it to be a bug in this very package.

**Comment by ascoril** [comment]
Will there be a fix available, or we just have to live with it. I was trying to use the library in android. If we just have to live with it, is there any other available library which does the same thing that you know of ?

**Comment by fge** [comment]
Not sure what you mean.

As I mentioned, to my eyes the bug is not with my library but with zygote. You should ask them about the bug.

I do know that there is another lurking bug with Android that I'm aware of and which is easily fixable, but it has nothing to do with this one...

**Comment by ascoril** [comment]
I have to check,  but zygoteinit$methodandargscaller is just an exception which is thrown by the "com.android.internal.os"

**Comment by ascoril** [comment]
I have found out the issue. It seems there is an existing schema file in json-schema-core-1.2.5.jar under the draftv3 and draftv4 folders. Which is a duplicate of the schema files under draftv3 and draftv4 under json-schema-validator-2.2.6.jar. So gradle ask to exclude the schema file as: 

packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'LICENSE'
        exclude 'draftv3/schema'
        exclude 'draftv4/schema'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/ASL-2.0.txt'
        exclude 'META-INF/LGPL-3.0.txt'
    }

On doing so, the above exception comes

**Comment by fge** [comment]
That META-INF problem _again_?

OK, then this _is_ related to the bug I already know, but my word the exception is unclear...

**Comment by KalinKanev** [comment]
You can use new gradle packagin options now 
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/ASL-2.0.txt'
        exclude 'META-INF/LGPL-3.0.txt'
        exclude 'META-INF/LICENSE.txt'
        pickFirst 'draftv3/schema'
        pickFirst 'draftv4/schema'
    }

But I get exception during validation. Have you managed to get it working on Android at all ?

**Comment by box-jhuffaker** [comment]
Here is likely what is throwing:
    static {
        final Context ctx = Context.enter();
        try {
            SCOPE = ctx.initStandardObjects(null, false);
            ctx.evaluateString(SCOPE, jsAsString, "re", 1, null);
            REGEX_IS_VALID = (Function) SCOPE.get("regexIsValid", SCOPE);
            REG_MATCH = (Function) SCOPE.get("regMatch", SCOPE);
        } finally {
            Context.exit();
        }
    }

**Comment by box-jhuffaker** [comment]
Not sure if the Rhino version you are using doesn't have a method that the version that was tested against uses.

**Comment by KalinKanev** [comment]
I'm using this repository with gradle:

compile 'com.github.fge:json-schema-validator:2.2.6'

Am I missing something ?

**Comment by box-jhuffaker** [comment]
Sorry I was assuming someone was incorporating a different version of rhino (a javascript evaluator originally by mozilla) which was throwing an UnsupportedOperationException in the code above.

After a tiny bit more research this is probably your problem:
http://stackoverflow.com/questions/3859305/problems-using-rhino-on-android

If I get a chance I'll try to get a pull request ready to do a:
cx.setOptimizationLevel(-1);

I'd probably want to make it configurable for android users to avoid a potential perf regression on other JRE's.   On the other side I'd love to remove the rhino dependency, unfortunately the json-schema says the pattern matches are javascript regexps, so that was the rationale for bringing it in in the first place.

**Comment by KalinKanev** [comment]
After I posted yesterday I tried researching on the net. Unfortunately Rhino knowledge is scarce and Rhino+Android obviously don't play together. If you are able to make that contribution I'll be very grateful. I tested your fork of this repository but to the same result.

**Comment by box-jhuffaker** [comment]
Build incoming, can't guarantee it will work or that you won't hit another problem, as I don't have an android env setup.

**Comment by box-jhuffaker** [comment]
https://github.com/box-metadata/json-schema-core/pull/2

**Comment by KalinKanev** [comment]
I'm trying to test any minute now.

**Comment by box-jhuffaker** [comment]
I will let you know when I've pushed a build.  Unfortunately it takes a
little bit to work its way through oss sonaytype.    The version when it is
published will be com.box.json-schema-validator 2.2.9

**Comment by box-jhuffaker** [comment]
Doing the build and publish now.  It should probably be up in 15-20
minutes.  2.2.9.

**Comment by box-jhuffaker** [comment]
you manage to try it out Kalin?

**Comment by KalinKanev** [comment]
I just tried but dependencies are not resolving correctly the way I try to pull them. Could you publish the version under Releases ?

**Comment by box-jhuffaker** [comment]
It looks published in Releases under com.box, json-schema-validator v2.2.9 to me.

**Comment by KalinKanev** [comment]
Indeed ! I should stop working in sleep deprived state :) 
The fix IS working. Thank you, Box !

**Comment by box-jhuffaker** [comment]
yeah, sleep deprivation doesn't help anyone! :)

glad you managed to get it stood up, hope the project helps you.

**Comment by uberchilly** [comment]
What is the exact fix for this? To use 
 implementation 'com.box:json-schema-validator:2.2.10' 
?

**Comment by Capstan** [comment]
https://github.com/java-json-tools/json-schema-validator#gradlemaven Modern version is v2.2.14. I don't know if it currently works, as we have no continuous integration testing Android builds. If someone familiar with https://docs.travis-ci.com/user/languages/android/ wanted to assist getting android builds running, I would accept PRs.
