### ISSUE TITLE
JsonSchema.class is final :((

### ISSUE THREAD

**Issue by bgalek** [java-json-tools/json-schema-validator#174]
JsonSchema.class is final, so I'm not able to stub it in my tests (Spock Framework for example). 
Could you possibly make JsonSchema not final class or extract interface there?

I don't see any benefit having this class as final one. If some JsonSchema.class methods shouldn't be overriden then make them final (not the whole class)

I can make PR if you agree with this.

**Comment by huggsboson** [comment]
Hi @bgalek,  fge hasn't been merging patches for a while.  We've been accepting pull requests on our fork at crate-metadata/json-schema-validator and publishing builds to maven central @ net.box#json-schema-validator.  We'll gladly work with him to remerge the changes if he comes back.

**Comment by dolmen** [comment]
@huggsboson If your fork is maintained, why don't you update the README in your fork?

**Comment by huggsboson** [comment]
@dolmen I'll update it on Monday.

**Comment by huggsboson** [comment]
I updated the readme.  I'm in contact with fge about potentially getting access to this repo and his maven central.

**Comment by daveclayton** [comment]
Hi @huggsboson happy to discuss remerging the changes

**Comment by huggsboson** [comment]
fantastic.  I'm at jhuffaker at box.com.  Would be happy to send some pull requests.  Super happy to have a proper maintainer back in here.

**Comment by bgalek** [comment]
i see interface extracted, gr8, thx!
