### ISSUE TITLE
Broken JavaDoc and code samples link in README

### ISSUE THREAD

**Issue by nodanaonlyzuul** [java-json-tools/json-schema-validator#195]
The  "code samples" and "Javadoc" links under the "current stable version: 2.2.6" and "old stable version: 2.0.4" bullet points are broken as of now.

The subdomain should change:

Links that are going to http://**fge**.github.io/json-schema-validator/2.2.x/index.html should go to 
http://**daveclayton**.github.io/json-schema-validator/2.2.x/index.html.

**Comment by smarkwell** [comment]
It appears that the new correct URL is http://java-json-tools.github.io/json-schema-validator/2.2.x/index.html

**Comment by smarkwell** [comment]
This is fixed in the current README.md.  Would propose closing this issue as fixed

**Comment by nodanaonlyzuul** [comment]
Sold! Seems like they've changed a few times since this was originally opened.
Thanks for checking back in on the ticket.
