### ISSUE TITLE
When set "optional" attribute and schemas is incorrect, we get an error about unknown keyword

### ISSUE THREAD

**Issue by SaneQ** [java-json-tools/json-schema-validator#208]
correct error, if delete "optional" attribute is:
com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: instance type (boolean) does not match any allowed primitive type (allowed: ["string"])

if add "optional" attribute, error will be:
com.github.fge.jsonschema.core.exceptions.ProcessingException: fatal: the following keywords are unknown and will be ignored: [optional]

I think it's from fix draft-03
*  Replaced "optional" attribute with "required" attribute.

**Comment by jlolling** [comment]
the optional attribute is replaced. I mean, this issue can be closed.
