### ISSUE TITLE
Update libphonenumber dependency to 7.2.3 or later

### ISSUE THREAD

**Issue by msymons** [java-json-tools/json-schema-validator#225]
Update com.googlecode.libphonenumber:libphonenumber from 6.2 to 7.2.3 or later.  Current version is 8.3.3.

This [addresses](https://github.com/googlei18n/libphonenumber/pull/934) an XSS vulnerability

The vulnerability is identified in Sonatype Nexus IQ analysis with reference SONATYPE-2015-0090.

Would you like me to do a PR?

**Comment by Capstan** [comment]
Fixed in commit c2379dcfdf743d3ccba8bf54f9168ee2c296951f
