### ISSUE TITLE
Invalid discriminator "value" causes NPE 

### ISSUE THREAD

**Issue by tvdinh** [java-json-tools/json-schema-validator#230]
Hi,

Say I have the following schema:
```json
   "Pet": {
      "type": "object",
      "discriminator": "petType",
      "properties": {
        "name": {
          "type": "string"
        },
        "petType": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "petType"
      ]
    },
    "Dog": {
      "description": "A representation of a dog",
      "allOf": [
        {
          "$ref": "#/definitions/Pet"
        },
        {
          "type": "object",
          "properties": {
            "packSize": {
              "type": "integer",
              "format": "int32",
              "description": "the size of the pack the dog is from",
              "default": 0,
              "minimum": 0
            }
          },
          "required": [
            "packSize"
          ]
        }
      ]
    }
```
And I'm validating the following json object against Pet (So I wrongly put it a "petType" that is not defined in schema.):
```
{
"name":"Kiki",
"petType":"Tiger",
"packSize":32
}
```
The validation results in a NPE: 
```  com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException  ```
Next, if I validate the following:

```
{
"name":"Kiki",
"petType":"Dog",
"packSize":"Not-A-Number"
}
```
It seems to ignore the validation for Dog, and returns no-error when it should give me a complain on the "packSize" not being an Integer.

My questions are:

1. Is the non-existence of petType "Tiger" causing the NPE in the first place ?  Nevertherless, should it be a proper validation error, like "discriminator-Tiger-undefined" ?
2. Why is (or should) the validation of the packSize in  the second validation ignored ?

Thanks!

**Comment by tvdinh** [comment]
Any comment ?

**Comment by jfnavin** [comment]
@tvdinh - the `discriminator` is an extension to JSON Schema specific to Swagger/OpenAPI.

There is custom handling of this field in the `swagger-request-validator` (which is where I'm guessing you're seeing the problems). Its probably better to open a ticket against that project for these specific issues.

Cheers,
James

**Comment by tvdinh** [comment]
Thanks @jfnavin  for comment.
