### ISSUE TITLE
Documentation link not working

### ISSUE THREAD

**Issue by g3blv** [java-json-tools/json-schema-validator#233]
I tried the document link http://huggsboson.github.io/json-schema-validator/2.2.x/index.html but I couldn't get it to work.

**Comment by huggsboson** [comment]
Is that link in the README somewhere?

**Comment by g3blv** [comment]
It is here https://github.com/java-json-tools/json-schema-validator/issues/229 :)

**Comment by huggsboson** [comment]
The README was already updated to:
http://java-json-tools.github.io/json-schema-validator/2.2.x/index.html

Hopefully that is the last move for a while.

**Comment by g3blv** [comment]
Thanks
