### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by g3blv** [java-json-tools/json-schema-validator#234]
Sorry for posting this as an issue but I couldn't find the information I'm looking for. I've tried to see if there is somewhere to post general questions around using json-schema-validator. I saw that there is a Google Group but I couldn't see any recent posts, there is also a tag on Stackoverflow but I'm not sure how active it is. Is there a preferable way to post general questions?

**Comment by huggsboson** [comment]
I think the best spot for now is as issues (maybe with RFI in the title).  I don't watch the google group or stackoverflow.  You could try all 3 and see which is best and quickest.
