### ISSUE TITLE
patternProperties does not work

### ISSUE THREAD

**Issue by kxg125** [java-json-tools/json-schema-validator#239]
Schema:
`{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "patternProperties": {
        "^[0-9]$": {
			"type" : "boolean"			
        }
    }
}`

json:
`{
    "abc" : true
}`

Expected : fail
Result: pass

**Comment by p-bakker** [comment]
I think this is not a bug. you haven't specified `"additionalProperties": false`, so any property goes

**Comment by kxg125** [comment]
Thanks for the response! Sorry i did not completely understand the answer; the reason why the validation should fail is that the key "abc" does not match the regex(patternProperties) in the schema. In my application the key is dynamic and is generated at runtime.
This should be a valid json:
{"1":true} or {"9":false}

**Comment by kxg125** [comment]
Oh, my bad. Got it now. :) Thanks.

**Comment by p-bakker** [comment]
You are not restricting the properties of your object to only the ones that match the patternProperties.

Unless you add `"additionalProperties": false` like below, the JSON is valid if it contains any other property besides the ones that match your pattern
{ 
"$schema": "http://json-schema.org/draft-04/schema#", 
"definitions": {}, 
"patternProperties": { 
   "^[0-9]$": {
      "type" : "boolean" 
   } 
}
"additionalProperties": false
 }
