### ISSUE TITLE
Getting error even on running example

### ISSUE THREAD

**Issue by usamaB** [java-json-tools/json-schema-validator#264]
Hi, All. Im trying to use this library for schema validation but whilst running the example im getting this error.
I have a big POM file. I have added the 
<dependency>
    <groupId>com.github.java-json-tools</groupId>
    <artifactId>json-schema-validator</artifactId>
    <version>2.2.10</version>
</dependency>
In the pom file. 
Whats the issue I dont understand and how to debug and fix the issue?

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Queues.newArrayDeque()Ljava/util/ArrayDeque;
	at com.github.fge.jsonschema.processors.validation.ValidationStack.<init>(ValidationStack.java:70)
	at com.github.fge.jsonschema.processors.validation.InstanceValidator.<init>(InstanceValidator.java:86)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:54)
	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
	at com.github.fge.jsonschema.main.JsonSchemaImpl.doValidate(JsonSchemaImpl.java:77)
	at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:100)
	at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:110)
```

**Comment by elreydetodo** [comment]
`Queue#newArrayDeque` was added as part of [Guava 12.0](https://google.github.io/guava/releases/23.0/api/docs/src-html/com/google/common/collect/Queues.html#line.75). Either you don't have a dependency on Guava (maybe someone excluded it in your pom?) or it's older than 12.0 (which was released on 2012-04-30). The former seems more likely.

**Comment by huggsboson** [comment]
Agreed make sure you include a somewhat modern version of guava.

**Comment by huggsboson** [comment]
If that doesn't solver you're problem feel free to re-open.

**Comment by darkorion** [comment]
Hello! I have same issue. I tried to add various version of guava, nothing changes.

error:

> java.lang.NoSuchMethodError: com.google.common.collect.Queues.newArrayDeque()Ljava/util/ArrayDeque;
> 
> 	at com.github.fge.jsonschema.processors.validation.ValidationStack.<init>(ValidationStack.java:70)
> 	at com.github.fge.jsonschema.processors.validation.InstanceValidator.<init>(InstanceValidator.java:86)
> 	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:54)
> 	at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34)
> 	at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79)
> 	at com.github.fge.jsonschema.main.JsonValidator.validate(JsonValidator.java:104)
> 	at com.github.fge.jsonschema.main.JsonValidator.validate(JsonValidator.java:124)

code:
> JsonNode parsedObject = mapper.readTree(object);
> JsonNode parsedSchema = mapper.readTree(schema);
> JsonValidator validator = JsonSchemaFactory.byDefault().getValidator();
> ProcessingReport r1 = validator.validate(parsedSchema, parsedObject);

pom:

>         <dependency>
>             <groupId>com.fasterxml.jackson.dataformat</groupId>
>             <artifactId>jackson-dataformat-yaml</artifactId>
>             <version>2.9.9</version>
>         </dependency>
>         <dependency>
>             <groupId>com.fasterxml.jackson.core</groupId>
>             <artifactId>jackson-databind</artifactId>
>             <version>2.9.9</version>
>         </dependency>
>         <dependency>
>             <groupId>com.github.java-json-tools</groupId>
>             <artifactId>json-schema-validator</artifactId>
>             <version>2.2.10</version>
>         </dependency>
>         <dependency>
>             <groupId>com.google.guava</groupId>
>             <artifactId>guava</artifactId>
>             <version>16.0.1</version>
>         </dependency>

**Comment by darkorion** [comment]
Also i dont use any version of guava at my project, just add to try advice above.
