### ISSUE TITLE
Multiple schema json files

### ISSUE THREAD

**Issue by AlexTo** [java-json-tools/json-schema-validator#274]
Hi
May I know how can I validate with multiple schema json files. Have several files like this [TincanSchema](https://github.com/RusticiSoftware/TinCanSchema/tree/master/1.0.1)

I need a way to load all the schema into the validator because each schema has an Id and they are referencing each other via $ref.

Previously I have used play-json-schema-validator but it is only available in Scala. The library allows me to do something like this:

![untitled](https://user-images.githubusercontent.com/296212/44567730-249e2d80-a7b7-11e8-8761-fdf7b5c11563.png)

It also support `format` as well.

How can I do the same thing with this library :( 

Thanks

**Comment by Murik** [comment]
Why it closed without any answer?
