### ISSUE TITLE
Missing release entries for 2.2.9 & 2.2.10

### ISSUE THREAD

**Issue by Capstan** [java-json-tools/json-schema-validator#287]
[Maven's v2.2.9](https://repo1.maven.org/maven2/com/github/java-json-tools/json-schema-validator/2.2.9/) shows it was released 2018-05-12
[Maven's v2.2.10](https://repo1.maven.org/maven2/com/github/java-json-tools/json-schema-validator/2.2.10/) shows it was released 2018-05-16

* Neither show up on the [Releases](https://github.com/java-json-tools/json-schema-validator/releases) page. 
* Neither have an entry on the [ChangeLog](https://github.com/java-json-tools/json-schema-validator/wiki/ChangeLog_22x)

**Comment by Capstan** [comment]
The changelog was apparently already reported in #272 .

**Comment by Capstan** [comment]
From spelunking, it appears that 2.2.10 is a fix release, rolling back the date-time validator (#262) added in 2.2.9 (#235), so perhaps 2.2.10 == 2.2.8?

**Comment by Capstan** [comment]
And the [wiki](https://github.com/java-json-tools/json-schema-validator/wiki) is out of date as well, pointing at stable version 2.2.5.

**Comment by daniela-waranie** [comment]
README.md is saying "current stable version: 2.2.10".
I would love to get a jar file of 2.2.10 to run it from command line.
Hope this will be available soon.

**Comment by Capstan** [comment]
2.2.11 is out, along with companion releases for jackson-coreutils and json-schema-core. You can find the binaries at https://repo1.maven.org/maven2/com/github/java-json-tools/json-schema-validator/2.2.11/ and peer directories.

**Comment by Capstan** [comment]
The remaining work would be to add the explicit tags for the commits representing 2.2.9, 2.2.10. @huggsboson , can you do that and/or specify what those tags were here? My best guesses are:

- 2.2.9's bits on maven central have the date 2018-05-12 but is missing commit 70ae8c0, so is probably commit 728b3da.
- 2.2.10's bits on maven central have the date 2018-05-16 and is probably commit 0992fe1.

**Comment by brutzman** [comment]
Latest advertised version of this library is 2.2.11, agreed that having shadow jar is helpful.

MVN central is a few years old at v2.2.6:
https://mvnrepository.com/artifact/com.github.fge/json-schema-validator

Wondering when support for current JSON Schema Draft 2019-09 is contemplated?

TIA for all efforts.

**Comment by Capstan** [comment]
@brutzman MVN central will not be updated at com.github.fge, per the [README](https://github.com/java-json-tools/json-schema-validator/blob/master/README.md). Try https://mvnrepository.com/artifact/com.github.java-json-tools/json-schema-validator.

There's no existing plan to fund support for Draft 05 - 09, not that we don't want that support. I haven't done a scoping operation for any of it, and as I've only come onboard recently through volunteering to overhaul Google's internal use of the library, which required deps fixes to avoid CVEs in dependent libraries, my context about the newer drafts is super limited. I would be happy to accept contributions so long as there's a mini-design doc for implementing them reviewed first.

**Comment by brutzman** [comment]
Thanks for the update.  Hope you get there someday, v4 is pretty far back from 2019 09... hopefully a stable outcome for the json schema saga is in sight.

I followed your links and tested the latest jar upgrade json-schema-validator-2.2.11.jar but it failed to launch as follows.  Previously tested json-schema-validator-2.2.6-lib.jar succeeds.

Ant:
        <echo>HelloWorld.json creation with X3dToJson.xslt</echo>
        
        <Saxon9  scene="HelloWorld"
            stylesheet="${stylesheet.dir}/X3dToJson"
             extension="json"
				expand="on"/>
        <echo>HelloWorld.json validation checking with jslint using ${jslint.jar}</echo>
        <java classname="com.googlecode.jslint4java.cli.Main" classpath="${jslint.jar}" fork="${fork}">
            <arg value="HelloWorld.json"/>
        </java>
        <echo>HelloWorld.json validation checking with ${json-schema-validator.jar}</echo>
        <java jar="${json-schema-validator.jar}" fork="${fork}">
            <arg value="../../../../specifications/x3d-3.3-JSONSchema.json"/>
            <arg value="HelloWorld.json"/>
        </java>

Output console excerpt:

HelloWorld.json creation with X3dToJson.xslt
HelloWorld.json validation checking with jslint using lib/jslint4java-2.0.5.jar
HelloWorld.json validation checking with lib/json-schema-validator-2.2.11.jar
Error: Unable to initialize main class com.github.fge.jsonschema.main.cli.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple/HelpFormatter
Java Result: 1

Good luck with your work.

**Comment by Capstan** [comment]
@brutzman In the case the following troubleshooting notes don't resolve it, please file this as a separate issue, since it's unrelated to the release entries issue. The variant on Maven is not a fat or full jar, and only contains jsonschema itself, and no dependent libraries. Does your Ant integrate with Maven to download the other dependent jars?

**Comment by huggsboson** [comment]
@Capstan 

I'm creating tags for:
2.2.10 == 0992fe13bc1b788480bdd4fa1a4f652299970b49
2.2.9  == 70ae8c09650faccd685441bd6e984ddf380ea3d5

It looks like you already updated release notes, the one note is that I believe 2.2.9 included changed the email validation in commit:
https://github.com/java-json-tools/json-schema-validator/commit/70ae8c09650faccd685441bd6e984ddf380ea3d5


Thank you!

**Comment by huggsboson** [comment]
I tried creating releases from the tags but github is creating way more info than I'm entering and I haven't worked out how to remove them.

**Comment by huggsboson** [comment]
Removed the errant releases I created.  Releases tag looks good.
