### ISSUE TITLE
Draft 06 specs for exclusiveMininum not respected

### ISSUE THREAD

**Issue by slisaasquatch** [java-json-tools/json-schema-validator#302]
This is the code I'm using to validate the schema:
```java
ProcessingReport r = JsonSchemaFactory.byDefault().getSyntaxValidator().validateSchema(schema);
System.out.println(r.isSuccess());
```
And here are the sample schemas I'm using:
1.
```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Minimum",
    "type": "integer",
    "exclusiveMinimum": 0
}
```
2.
```json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Test Minimum",
    "type": "integer",
    "minimum": 0,
    "exclusiveMinimum": true
}
```
The first schema should be valid with draft 06, but this library considers it invalid.
The second schema is valid with draft 04, but should be invalid with draft 06, and this library considers it valid.

**Comment by ethanharlig** [comment]
There's an [open issue](https://github.com/java-json-tools/json-schema-validator/issues/226) to support newer schemas than draft 04.

**Comment by slisaasquatch** [comment]
I'll close this ticket then.
