### ISSUE TITLE
how to get all invalid fields in json-schema-validator for java application

### ISSUE THREAD

**Issue by ZuoJunLN** [java-json-tools/json-schema-validator#304]
when I use validate(schema, instance) function to validate json instance, if this json instance includes multiple invalid fields, I only get one error message. 
Is there any way we can get all invalid fields in one validate() function call?

Sorry, I find the validate() function has the third param can do that.

**Comment by dheepakji** [comment]
@ZuoJunLN Which library you are using for comparing the schema and how did you get the invalid fields. If you describe it would be helpful. Thanks a lot in advance!

**Comment by ZuoJunLN** [comment]
Thanks for your reply.
From the JsonValidator class, function validate(), if I provide the third parameter with value “true”, I will get all invalid fields in my json instance.

Thanks!
Jun
