### ISSUE TITLE
ClassNotFound: JsonSchemaFactory

### ISSUE THREAD

**Issue by YashaShah13** [java-json-tools/json-schema-validator#310]
I am using following dependency in pom. xml. It works fine

<dependency>
    <groupId>com.github.java-json-tools</groupId>
    <artifactId>json-schema-validator</artifactId>
    <version>2.2.11</version>
</dependency>

But if I include all the JARs downloaded by maven as external jar it throws ClassNotFound Error for com.github.fge..jsonSchema.JsonSchemaFactory.class

**Comment by huggsboson** [comment]
I checked out maven central and things look pretty good on our end.  Any chance you can post more info about your classpath?

**Comment by huggsboson** [comment]
Are you running this from the command line or as a library in another service?

**Comment by Capstan** [comment]
Since we haven't heard back, I'm going to close this issue. Please feel free to re-open if you have more data.
