### ISSUE TITLE
Generate Java classes from JSON Schema

### ISSUE THREAD

**Issue by dportabella** [java-json-tools/json-schema-validator#32]
Hi,

can the library fge/json-schema-validator generate Java classes from a JSON Schema?
otherwise, is it planned to add this feature some time soon?

if not, can you suggest a solution?
I've read about "jsonschema2pojo". is that a good solution?

best regards,
David

**Comment by joelittlejohn** [comment]
But yes I see what you mean now Francis. I wasn't aware of your 'processor'
construct and how these are chained together.

Please feel free to give me a shout if you have any more questions.
