### ISSUE TITLE
Release new minor version of java-json-tools repos w/ Java 7 and Guava fixes.

### ISSUE THREAD

**Issue by Capstan** [java-json-tools/json-schema-validator#322]
/cc @huggsboson 

I probably have one more set of cleanup changes for this repo, but I'd like to do another dot release with all the recent cleanup work in here, probably at the end of November.

I'm inclined to just bump the minor version to the next even number for each. Please chime in if you think otherwise.

Is there anything else we'd want to include before releasing?

**Comment by huggsboson** [comment]
I trust your judgement.

**Comment by Capstan** [comment]
Released as of today.
