### ISSUE TITLE
Possible to customize messages?

### ISSUE THREAD

**Issue by dsjellz** [java-json-tools/json-schema-validator#55]
As far as i can see, all error messages are stored as enumerations and cannot be modified via any configuration? Is this correct?

For example, changing the message from 'input is not a valid email address' to 'The value you have entered is not a valid email address'.

Thanks!

**Comment by iyu-zz** [comment]
I'm working on a use case where this feature ("custom validation error messages") can be very useful.   After doing the Json Schema validation and getting a report with list of validation errors, i want to override the messages with a set of custom messages, and then push the messages list to REST API response.   By reading the logs here, it looks like this lib + msg-simple may give me what i want.   Could you provide a simple example for doing this?  Appreciate it.
