### ISSUE TITLE
Is it possible to add line number into the Report?

### ISSUE THREAD

**Issue by feiniao0308** [java-json-tools/json-schema-validator#59]
It's different to locate the error in current Report format as follows for large JSON file. Is it possible to add line number into Report to denote which line is the pointer(schema or instance)?

com.github.fge.jsonschema.report.ListProcessingReport: failure--- 
BEGIN MESSAGES 
---error: instance type does not match any allowed primitive type
    level: "error"
    schema: {"loadingURI":"#","pointer":"/properties/version"}
    instance: {"pointer":"/version"}
    domain: "validation"
    keyword: "type"
    expected: ["integer"]
    found: "number"
---  END MESSAGES  ---

Thanks,
Hai

**Comment by bharatsavanur11** [comment]
I have completed a project in java for json validation with line number using jackson. Basically as @fge has coorectly said, we have to maually parse the data and create JSONNode objects at runtime. 

Please let me know incase of any help is needed.

**Comment by pulpham** [comment]
@bharatsavanur11 
Could you please send me your implementation? It will help me so much to solve problem in my project.
Thank you in advance!
My email: hungfq@gmail.com

**Comment by ostwalankit** [comment]
@bharatsavanur11 , Can you please share your implementation over here or on email ostwalankit@gmail.com . It will help me solve my issue. I really appreciate your help. Thanks.
