### ISSUE TITLE
invalid schema, cannot continue

### ISSUE THREAD

**Issue by kalyanir** [java-json-tools/json-schema-validator#79]
I create schema with the following string:

"{ \"$schema\": \"http://json-schema.org/draft-04/schema#\", " +
                "\"title\": \"dropboxSchema\", " +
                "\"type\": \"object\", " +
                "\"properties\": { " +
                "\"numBytes\": { " +
                "\"type\": \"long\"" +
                "} " +
                "}, " +
                "\"required\":[ \"numBytes\"], " +
                "\"additionalItems\": false " +
"} "

When I try to validate a JsonNode with this schema, I get "com.github.fge.jsonschema.exceptions.InvalidSchemaException: invalid schema, cannot continue" error. 

What is the error with schema? If the schema is incorrect, why does it not throw an exception when the schema is created?

**Comment by nhatnguyen26** [comment]
This is an old question, but might I ask, If I have a new created schema, is there a way to validate the schema before validating the actual json? I am trying to use the newest version.

**Comment by fge** [comment]
@nhatnguyen26 yes there is; just grab the `SyntaxValidator` from your `JsonSchemaFactory` ([link to javadoc](http://fge.github.io/json-schema-validator/2.2.x/com/github/fge/jsonschema/main/JsonSchemaFactory.html#getSyntaxValidator()))
