### ISSUE TITLE
JSON Schema links

### ISSUE THREAD

**Issue by ghost** [java-json-tools/json-schema-validator#80]
Hello,

I'm using your library and i'm looking for how to deal with "links" keywords in my JSON Schema.
This links keyword is DRAFT V4 compliant, however a warning is thrown : 

warning: the following keywords are unknown and will be ignored: [links]
    level: "warning"
    schema: {"loadingURI":"#","pointer":""}
    domain: "syntax"
    ignored: ["links"]

Please can anyone help?

**Comment by muditsri** [comment]
I am using version: 2.3.8 but still getting warnings: warning: the following keywords are unknown and will be ignored: [elementName]
