### ISSUE TITLE
"allOf" with "additionalProperties" = false

### ISSUE THREAD

**Issue by mlito** [java-json-tools/json-schema-validator#91]
Hello 
I have question regarding usage of "allOf" with "additionalProperties" = false. 
I saw that there is similar issue https://github.com/fge/json-schema-validator/issues/88
Let's consider sample from tutorial (http://spacetelescope.github.io/understanding-json-schema/)

{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"]
    }
  },

  "type": "object",

  "properties": {
    "billing_address": { "$ref": "#/definitions/address" },
    "shipping_address": {
      "allOf": [
        { "$ref": "#/definitions/address" },
        { "properties":
          { "type": { "enum": [ "residential", "business" ] } },
          "required": ["type"]
        }
      ]
    } 

  }
}

and here is valid instance

{
      "shipping_address": {
        "street_address": "1600 Pennsylvania Avenue NW",
        "city": "Washington",
        "state": "DC",
        "type": "business"
      }
}

I need to ensure that all fields other that "street_address" , "city", "state" (from referenced address) and "type" (from "extended" object) will be invalid
I tried to add "additionalProperies":false in  address like this 

"address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city":           { "type": "string" },
        "state":          { "type": "string" }
      },
      "required": ["street_address", "city", "state"],
     "additionalProperies":false
    }

And in shipping_adress definition : 

"shipping_address": {
      "allOf": [
        { "$ref": "#/definitions/address" },
        { "properties":
          { "type": { "enum": [ "residential", "business" ] } },
          "required": ["type"]
        }
      ], 
      "additionalProperies":false
    } 

In both cases I got message ( checked on http://json-schema-validator.herokuapp.com/) about unwanted fields . 
As you mentioned in https://github.com/fge/json-schema-validator/issues/88 - it is not bug - is it correct ? 
Additional question : how can I ensure that 
1) "shipping_address" will be extension of  "address" 
2) No additional fields allowed for  "shipping_address"
Thanks in advance

**Comment by epoberezkin** [comment]
@fge, out of curiosity, do you imply that the validation result of "strictProperties" will be affected by "properties" etc. outside of the current schema object?
